### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by kroerig** [kroerig/openbiblio-german#7]
Encoding anpassen, damit Umlaute richtig dargestellt werden.
Wirkt sich auch auf die Suche aus.

**Comment by ThomasChr** [comment]
Ja, ich merke das auf meinem Server das installieren mit Beispieldaten abbricht wegen:
```
[Fri Sep 02 12:02:56.517615 2022] [php:error] [pid 15011] PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect string value: '\\xFCgte K...' for column 'description' at row 1 in /var/www/html/classes/QueryMysqli.php:78\nStack trace:\n
#0 /var/www/html/classes/QueryMysqli.php(78): mysqli_query()\n
#1 /var/www/html/classes/Query.php(76): QueryMysqli->query()\n
#2 /var/www/html/classes/Query.php(253): Query->_act()\n
#3 /var/www/html/classes/Query.php(258): Query->_exec()\n
#4 /var/www/html/classes/InstallQuery.php(130): Query->exec()\n
#5 /var/www/html/classes/InstallQuery.php(96): InstallQuery->executeSqlFile()\n
#6 /var/www/html/classes/InstallQuery.php(85): InstallQuery->executeSqlFilesInDir()\n
#7 /var/www/html/install/install.php(69): InstallQuery->freshInstall()\n
#8 {main}\n  thrown in /var/www/html/classes/QueryMysqli.php on line 78
```
Kommt aus der OpenBiblio.sql, so Zeile 689 , z.B. 'Bemerkung, hinzugefügte Kontrolle'.
In der Fehlermeldung dass \xFC ist das Byte für ein ISO-8859-1 'ü' - unter UTF-8 ist das "c3 bc" - Datenbank ist (per Default) komplett auf 'utf8mb4', auch die Tabelle sieht so aus:
```
mysql> show full columns from usmarc_indicator_dm;
+----------------+-------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| Field          | Type        | Collation          | Null | Key | Default | Extra | Privileges                      | Comment |
+----------------+-------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| tag            | smallint    | NULL               | NO   | PRI | NULL    |       | select,insert,update,references |         |
| indicator_nmbr | tinyint     | NULL               | NO   | PRI | NULL    |       | select,insert,update,references |         |
| indicator_cd   | char(1)     | utf8mb4_0900_ai_ci | NO   | PRI | NULL    |       | select,insert,update,references |         |
| description    | varchar(80) | utf8mb4_0900_ai_ci | NO   |     | NULL    |       | select,insert,update,references |         |
+----------------+-------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
```

Eventuell ist die DB-Connection noch auf ISO-8859-1? Sollte sie aber eigentlich ned sein.

**Comment by kroerig** [comment]
Die Umlaute sind auch in den Menüs kaputt.
![grafik](https://user-images.githubusercontent.com/5148795/188118719-ca06dd28-c1c4-44be-b2af-15bed3006b1e.png)

**Comment by ThomasChr** [comment]
Ja, ich denke bei einer vorhandenen Datenbank müssen da noch die Tabellen entsprechend nach UTF-8 konvertiert werden...
Aber alles in allem sieht das doch jetzt schon echt gut aus

**Comment by ThomasChr** [comment]
Erwartungsgemäß läuft das Install mit English problemlos durch. Naja, das will ich jetzt noch finden, dann muss es erstmal wieder reichen...

**Comment by kroerig** [comment]
Ich bearbeite schon mal die Lang-Files. Die Inhalte der Datenbank könenn wir uns später vornehmen. Hab noch genügend andere Fehlermeldungen.

**Comment by ThomasChr** [comment]
So, mit PR #8 läuft der Installer durch.
Er trägt in den Settings aber noch ISO-8859-1 für die HTML kodierung ein. Das sollte man evtl. noch in der Datei 'locale/de/sql/0.7.1/domain/settings.sql' ändern?

![grafik](https://user-images.githubusercontent.com/13014163/188124868-df469a42-84f3-4a82-9dd1-976472324d74.png)

Bei mir läufts jetzt jedenfalls erstmal. Und das auf einem frisch installieren Ubuntu 22.04 mit dem aktuellen PHP 8.1.9 - ich bin erstmal zufrieden.

**Comment by ThomasChr** [comment]
Jep, hier noch Umlaute kaputt:
![grafik](https://user-images.githubusercontent.com/13014163/188126195-efd37430-1987-4231-8a71-16108060bf7e.png)

**Comment by kroerig** [comment]
So, die Umlaute in den Menüs und Texten sollten jetzt stimmen, wenn ich nichts übersehen habe.

**Comment by kroerig** [comment]
Ich habe die Einstellungen bei mir jetzt auf UTF-8 geändert.

**Comment by ThomasChr** [comment]
Ist doch alles einfacher als gedacht :-)

**Comment by kroerig** [comment]
Da fehlen sicher noch ein paar Sachen. Die Settings.sql habe ich angepasst. Kommt beim nächsten Commit mit.

**Comment by kroerig** [comment]
Ich habe mal ein ALTER TABLE über alle Tabllen laufen lassen. Neuen SQL-Dump erstellt.

**Comment by kroerig** [comment]
hm. Irgendwas passt das mit der Konvertierung der Datenbank nicht:
![grafik](https://user-images.githubusercontent.com/5148795/188328537-7350f0a8-a6a5-4690-9e84-fe8a59fb9f3c.png)

**Comment by kroerig** [comment]
Die Spielwiese ist eine MySQL 8 (Ubuntu 20.04), das System in der Schule eine MariaDB 10 (Debian 10)

**Comment by ThomasChr** [comment]
Evtl. ist PHP da nicht auf utf-8 eingestellt. Gibt verschiedene Stellen wo man das drehen kann.

**Comment by kroerig** [comment]
ein ` $this->query("SET CHARACTER SET utf8mb4");` hilft.

**Comment by ThomasChr** [comment]
Dann ist die Datenbank per default nicht auf utf-8 eingestellt. Meine frisch installierte war das eben schon.
Das macht Sinn :-)

**Comment by kroerig** [comment]
Das kann sein, die stammt aus einem Debian 7.

**Comment by ThomasChr** [comment]
Hier bräuchten wir dann noch eine Automatik die entweder eine ISO-8859-1 Datenbank automatisch komvertiert oder aber transparent umwandelt!
