### ISSUE TITLE
Neues Medium anlegen geht nicht

### ISSUE THREAD

**Issue by ThomasChr** [kroerig/openbiblio-german#9]
```
[Fri Sep 02 13:00:55.467001 2022] [php:error] [pid 15017] PHP Fatal error:  Uncaught Error: Call to undefined method UsmarcTagDmQuery::Query() in /var/www/html/classes/UsmarcTagDmQuery.php:22\nStack trace:\n
#0 /var/www/html/catalog/biblio_fields.php(19): UsmarcTagDmQuery->__construct()\n
#1 /var/www/html/catalog/biblio_new.php(136): include('...')\n
#2 /var/www/html/catalog/biblio_new.php(16): showForm()\n
#3 {main}\n  thrown in /var/www/html/classes/UsmarcTagDmQuery.php on line 22
```

**Comment by kroerig** [comment]
Probier bitte mal, wo er jetzt stecken bleibt, aber den `$this->Query` sollte ich überall beseitigt haben.

**Comment by kroerig** [comment]
klappt jetzt auch wieder:
https://github.com/kroerig/openbiblio-german/pull/12#issue-1360406887
